# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ------------- Tests ----------------
      
      - name: test and16
        run: |
          pytest hw/test_components.py -k and16
          
      - name: test mux2way
        run: |
          pytest hw/test_components.py -k test_mux2way

      - name: test mux4way
        run: |
          pytest hw/test_components.py -k test_mux4way

      - name: test mux8way
        run: |
          pytest hw/test_components.py -k test_mux8way

      - name: test barrelShifter
        run: |
          pytest hw/test_components.py -k barrelShifter
      
      - name: test or8way
        run: |
          pytest hw/test_components.py -k or8way
        
      - name: test deMux4way
        run: |
          pytest hw/test_components.py -k deMux4way
      
      - name: test orNway
        run: |
          pytest hw/test_components.py -k orNway
      
      - name: test deMux2way
        run: |
          pytest hw/test_components.py -k deMux2way
          
      - name: test deMux8way
        run: |
          pytest hw/test_components.py -k test_deMux8way
      
      - name: test bin2bcd
        run: |
          pytest hw/test_components.py -k test_bin2bcd
      


      # ----- ULA ------

      - name: test comparador
        run: |
          pytest hw/test_ula.py -k test_comparador
      
      - name: test inversor
        run: |
          pytest hw/test_ula.py -k test_inversor

      - name: test zerador
        run: |
          pytest hw/test_ula.py -k test_zerador
      
      - name: test add
        run: |
          pytest hw/test_ula.py -k test_add
      
      - name: test inc
        run: |
          pytest hw/test_ula.py -k test_inc
      
      - name: teste ula
        run: |
          pytest hw/test_ula.py -k test_ula
      
      # ------ SEQ -------
      - name: teste dff
        run: |
          pytest hw/test_seq.py -k test_dff
      
      - name: teste binaryDigit
        run: |
          pytest hw/test_seq.py -k test_binaryDigit
      
      - name: teste register8
        run: |
          pytest hw/test_seq.py -k test_register8
      
      - name: teste registerN
        run: |
          pytest hw/test_seq.py -k test_registerN
      
      - name: teste pc
        run: |
          pytest hw/test_seq.py -k test_pc
      
      - name: teste ram
        run: |
          pytest hw/test_seq.py -k test_ram

      # ------ ASSEMBLY -------

      # ------ ASSEMBLER -------

      - name: teste advanced
        run: |
          pytest sw/assembler/test_asmparser.py -k test_advanced

      - name: teste label
        run : |
          pytest sw/assembler/test_asmparser.py -k test_labol

      - name: teste symbol
        run : |
          pytest sw/assembler/test_asmparser.py -k test_symbol
      
      - name: teste CommandType
        run : |
          pytest sw/assembler/test_asmparser.py -k test_commandType

      - name: teste dest
        run : |
          pytest sw/assembler/test_asmcode.py -k test_dest

      - name: teste comp
        run : |
          pytest sw/assembler/test_asmcode.py -k test_comp
        
      - name: teste jump
        run : |
          pytest sw/assembler/test_asmcode.py -k test_jump

      - name: teste toBinary
        run : |
          pytest sw/assembler/test_asmcode.py -k test_toBinary
      
      - name: teste SymbolTable init
        run : |
          pytest sw/assembler/test_symboltable.py -k test_init
      
      - name: teste addEntry
        run : |
          pytest sw/assembler/test_symboltable.py -k test_addEntry
      
      - name: teste contains
        run : |
          pytest sw/assembler/test_symboltable.py -k test_contains
      
      - name: teste getAddress
        run : |
          pytest sw/assembler/test_symboltable.py -k test_getAddress
      
      - name: teste toBinary
        run : |
          pytest sw/assembler/test_asmcode.py -k test_toBinary
      
      - name: teste fillSymbolTtable_labels
        run : |
          pytest sw/assembler/test_asm.py -k test_fillSymbolTtable_labels
      
      - name: teste fillSymbolTtable_address
        run : |
          pytest sw/assembler/test_asm.py -k test_fillsymboltable_address
      
      - name: teste asm_run
        run : |
          pytest sw/assembler/test_asm.py -k test_asm_run
      
      - name: teste asm_hack
        run : |
          pytest sw/assembler/test_asm.py -k test_asm_hack

      # ------ VM TRANSLATOR -------
      - name: teste arithmetic_add
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_add

      - name: teste arithmetic_sub
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_sub

      - name: teste arithmetic_orr
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_orr

      - name: teste arithmetic_andd
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_andd

      - name: teste arithmetic_nott
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_nott

      - name: teste arithmetic_neg
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_neg

      - name: teste arithmetic_eq_false
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_eq_false

      - name: teste arithmetic_eq_true
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_eq_true

      - name: teste arithmetic_gt_false
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_gt_false

      - name: teste arithmetic_gt_true
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_gt_true

      - name: teste arithmetic_lt_false
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_lt_false

      - name: teste arithmetic_lt_true
        run: |
          pytest sw/vmtranslator/test_code_arithmetic.py -k test_lt_true

      - name: teste pop_local
        run: |
          pytest sw/vmtranslator/test_code_pop.py -k test_pop_local

      - name: teste pop_this
        run: |
          pytest sw/vmtranslator/test_code_pop.py -k test_pop_this

      - name: teste pop_that
        run: |
          pytest sw/vmtranslator/test_code_pop.py -k test_pop_that

      - name: teste pop_temp
        run: |
          pytest sw/vmtranslator/test_code_pop.py -k test_pop_temp

      - name: teste pop_pointer
        run: |
          pytest sw/vmtranslator/test_code_pop.py -k test_pop_pointer
      
      - name: teste push_constant
        run: |
          pytest sw/vmtranslator/test_code_push.py -k test_push_constant
      
      - name: teste push_local
        run: |
          pytest sw/vmtranslator/test_code_push.py -k test_push_local
      
      - name: teste push_argument
        run: |
          pytest sw/vmtranslator/test_code_push.py -k test_push_argument
      
      - name: teste push_this
        run: |
          pytest sw/vmtranslator/test_code_push.py -k test_push_this
      
      - name: teste push_that
        run: |
          pytest sw/vmtranslator/test_code_push.py -k test_push_that
      
      - name: teste push_temp
        run: |
          pytest sw/vmtranslator/test_code_push.py -k test_push_temp
      
      - name: teste push_pointer
        run: |
          pytest sw/vmtranslator/test_code_push.py -k test_push_pointer
      
      - name: teste goto_false
        run: |
          pytest sw/vmtranslator/test_code_goto.py -k test_goto_false
      
      - name: teste goto_true
        run: |
          pytest sw/vmtranslator/test_code_goto.py -k test_goto_true
